var searchData=
[
  ['background',['background',['https://doc.qt.io/qt-5/qmdiarea.html#background-prop',0,'QMdiArea']]],
  ['backgroundbrush',['backgroundBrush',['https://doc.qt.io/qt-5/qgraphicsscene.html#backgroundBrush-prop',0,'QGraphicsScene::backgroundBrush()'],['https://doc.qt.io/qt-5/qgraphicsview.html#backgroundBrush-prop',0,'QGraphicsView::backgroundBrush()']]],
  ['backgroundvisible',['backgroundVisible',['https://doc.qt.io/qt-5/qplaintextedit.html#backgroundVisible-prop',0,'QPlainTextEdit']]],
  ['basesize',['baseSize',['https://doc.qt.io/qt-5/qwidget.html#baseSize-prop',0,'QWidget']]],
  ['baseurl',['baseUrl',['https://doc.qt.io/qt-5/qtextdocument.html#baseUrl-prop',0,'QTextDocument']]],
  ['batchsize',['batchSize',['https://doc.qt.io/qt-5/qlistview.html#batchSize-prop',0,'QListView']]],
  ['blockcount',['blockCount',['https://doc.qt.io/qt-5/qtextdocument.html#blockCount-prop',0,'QTextDocument::blockCount()'],['https://doc.qt.io/qt-5/qplaintextedit.html#blockCount-prop',0,'QPlainTextEdit::blockCount()']]],
  ['blurhints',['blurHints',['https://doc.qt.io/qt-5/qgraphicsblureffect.html#blurHints-prop',0,'QGraphicsBlurEffect']]],
  ['blurradius',['blurRadius',['https://doc.qt.io/qt-5/qgraphicsblureffect.html#blurRadius-prop',0,'QGraphicsBlurEffect::blurRadius()'],['https://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#blurRadius-prop',0,'QGraphicsDropShadowEffect::blurRadius()']]],
  ['bottom',['bottom',['https://doc.qt.io/qt-5/qintvalidator.html#bottom-prop',0,'QIntValidator::bottom()'],['https://doc.qt.io/qt-5/qdoublevalidator.html#bottom-prop',0,'QDoubleValidator::bottom()']]],
  ['botvalue',['botValue',['../classmax_lib_qt_1_1controls_1_1_m_l_double_spin_box.html#a9ab6afeb7b945f7fba0bfe1fc12fa1e9',1,'maxLibQt::controls::MLDoubleSpinBox']]],
  ['bsptreedepth',['bspTreeDepth',['https://doc.qt.io/qt-5/qgraphicsscene.html#bspTreeDepth-prop',0,'QGraphicsScene']]],
  ['button',['button',['https://doc.qt.io/qt-5/qmouseeventtransition.html#button-prop',0,'QMouseEventTransition']]],
  ['buttonrepeatdelay',['buttonRepeatDelay',['../classmax_lib_qt_1_1controls_1_1_m_l_double_spin_box.html#ae0fd7c63770cebcde60bf22693ed8916',1,'maxLibQt::controls::MLDoubleSpinBox']]],
  ['buttonrepeatinterval',['buttonRepeatInterval',['../classmax_lib_qt_1_1controls_1_1_m_l_double_spin_box.html#a1961a2423bc91fa46a07b0d8523e41c9',1,'maxLibQt::controls::MLDoubleSpinBox']]],
  ['buttonsymbols',['buttonSymbols',['https://doc.qt.io/qt-5/qabstractspinbox.html#buttonSymbols-prop',0,'QAbstractSpinBox']]]
];
