var searchData=
[
  ['wascanceled',['wasCanceled',['https://doc.qt.io/qt-5/qprogressdialog.html#wasCanceled-prop',0,'QProgressDialog']]],
  ['whatsthis',['whatsThis',['https://doc.qt.io/qt-5/qwidget.html#whatsThis-prop',0,'QWidget::whatsThis()'],['https://doc.qt.io/qt-5/qaction.html#whatsThis-prop',0,'QAction::whatsThis()'],['https://doc.qt.io/qt-5/qshortcut.html#whatsThis-prop',0,'QShortcut::whatsThis()']]],
  ['wheelscrolllines',['wheelScrollLines',['https://doc.qt.io/qt-5/qstylehints.html#wheelScrollLines-prop',0,'QStyleHints::wheelScrollLines()'],['https://doc.qt.io/qt-5/qapplication.html#wheelScrollLines-prop',0,'QApplication::wheelScrollLines()']]],
  ['widgetresizable',['widgetResizable',['https://doc.qt.io/qt-5/qscrollarea.html#widgetResizable-prop',0,'QScrollArea']]],
  ['width',['width',['https://doc.qt.io/qt-5/qwindow.html#width-prop',0,'QWindow::width()'],['https://doc.qt.io/qt-5/qwidget.html#width-prop',0,'QWidget::width()']]],
  ['windowfilepath',['windowFilePath',['https://doc.qt.io/qt-5/qwidget.html#windowFilePath-prop',0,'QWidget']]],
  ['windowflags',['windowFlags',['https://doc.qt.io/qt-5/qwidget.html#windowFlags-prop',0,'QWidget::windowFlags()'],['https://doc.qt.io/qt-5/qgraphicswidget.html#windowFlags-prop',0,'QGraphicsWidget::windowFlags()']]],
  ['windowicon',['windowIcon',['https://doc.qt.io/qt-5/qguiapplication.html#windowIcon-prop',0,'QGuiApplication::windowIcon()'],['https://doc.qt.io/qt-5/qwidget.html#windowIcon-prop',0,'QWidget::windowIcon()'],['https://doc.qt.io/qt-5/qapplication.html#windowIcon-prop',0,'QApplication::windowIcon()']]],
  ['windowicontext',['windowIconText',['https://doc.qt.io/qt-5/qwidget-obsolete.html#windowIconText-prop',0,'QWidget']]],
  ['windowmodality',['windowModality',['https://doc.qt.io/qt-5/qwidget.html#windowModality-prop',0,'QWidget']]],
  ['windowmodified',['windowModified',['https://doc.qt.io/qt-5/qwidget.html#windowModified-prop',0,'QWidget']]],
  ['windowopacity',['windowOpacity',['https://doc.qt.io/qt-5/qwidget.html#windowOpacity-prop',0,'QWidget']]],
  ['windowtitle',['windowTitle',['https://doc.qt.io/qt-5/qwidget.html#windowTitle-prop',0,'QWidget::windowTitle()'],['https://doc.qt.io/qt-5/qdockwidget.html#windowTitle-prop',0,'QDockWidget::windowTitle()'],['https://doc.qt.io/qt-5/qgraphicswidget.html#windowTitle-prop',0,'QGraphicsWidget::windowTitle()']]],
  ['wizardstyle',['wizardStyle',['https://doc.qt.io/qt-5/qwizard.html#wizardStyle-prop',0,'QWizard']]],
  ['wordwrap',['wordWrap',['https://doc.qt.io/qt-5/qlabel.html#wordWrap-prop',0,'QLabel::wordWrap()'],['https://doc.qt.io/qt-5/qlistview.html#wordWrap-prop',0,'QListView::wordWrap()'],['https://doc.qt.io/qt-5/qtableview.html#wordWrap-prop',0,'QTableView::wordWrap()'],['https://doc.qt.io/qt-5/qtreeview.html#wordWrap-prop',0,'QTreeView::wordWrap()']]],
  ['wordwrapmode',['wordWrapMode',['https://doc.qt.io/qt-5/qtextedit.html#wordWrapMode-prop',0,'QTextEdit::wordWrapMode()'],['https://doc.qt.io/qt-5/qplaintextedit.html#wordWrapMode-prop',0,'QPlainTextEdit::wordWrapMode()']]],
  ['wrap',['wrap',['../classmax_lib_qt_1_1controls_1_1_m_l_double_spin_box.html#a8d9b61ec4e7ec9f461952b9f2ada69cb',1,'maxLibQt::controls::MLDoubleSpinBox']]],
  ['wraparound',['wrapAround',['https://doc.qt.io/qt-5/qcompleter.html#wrapAround-prop',0,'QCompleter']]],
  ['wrapping',['wrapping',['https://doc.qt.io/qt-5/qabstractspinbox.html#wrapping-prop',0,'QAbstractSpinBox::wrapping()'],['https://doc.qt.io/qt-5/qdial.html#wrapping-prop',0,'QDial::wrapping()']]],
  ['writingsystem',['writingSystem',['https://doc.qt.io/qt-5/qfontcombobox.html#writingSystem-prop',0,'QFontComboBox']]]
];
