var searchData=
[
  ['radius',['radius',['../class_rounded_message_box.html#a131913e282895d14529ceb52fe17848b',1,'RoundedMessageBox']]],
  ['rangeaccessflags',['RangeAccessFlags',['https://doc.qt.io/qt-5/qopenglbuffer.html#RangeAccessFlag-enum',0,'QOpenGLBuffer']]],
  ['readfunc',['ReadFunc',['https://doc.qt.io/qt-5/qsettings.html#ReadFunc-typedef',0,'QSettings']]],
  ['reference',['reference',['https://doc.qt.io/qt-5/qstringview.html#reference-typedef',0,'QStringView::reference()'],['https://doc.qt.io/qt-5/qlatin1string.html#reference-typedef',0,'QLatin1String::reference()'],['https://doc.qt.io/qt-5/qstring.html#reference-typedef',0,'QString::reference()'],['https://doc.qt.io/qt-5/qlist.html#reference-typedef',0,'QList::reference()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reference-typedef',0,'QVarLengthArray::reference()'],['https://doc.qt.io/qt-5/qvector.html#reference-typedef',0,'QVector::reference()'],['https://doc.qt.io/qt-5/qset.html#reference-typedef',0,'QSet::reference()'],['https://doc.qt.io/qt-5/qset-iterator.html#reference-typedef',0,'QSet::iterator::reference()'],['https://doc.qt.io/qt-5/qset-const-iterator.html#reference-typedef',0,'QSet::const_iterator::reference()'],['https://doc.qt.io/qt-5/qcborarray.html#reference-typedef',0,'QCborArray::reference()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#reference-typedef',0,'QFuture::const_iterator::reference()'],['https://doc.qt.io/qt-5/qjsonarray.html#reference-typedef',0,'QJsonArray::reference()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reference-typedef',0,'QLinkedList::reference()']]],
  ['relation',['Relation',['https://doc.qt.io/qt-5/qaccessible.html#RelationFlag-enum',0,'QAccessible']]],
  ['renderflags',['RenderFlags',['https://doc.qt.io/qt-5/qtextitem.html#RenderFlag-enum',0,'QTextItem::RenderFlags()'],['https://doc.qt.io/qt-5/qwidget.html#RenderFlag-enum',0,'QWidget::RenderFlags()']]],
  ['renderhints',['RenderHints',['https://doc.qt.io/qt-5/qpainter.html#RenderHint-enum',0,'QPainter']]],
  ['result',['Result',['https://doc.qt.io/qt-5/qgesturerecognizer.html#ResultFlag-enum',0,'QGestureRecognizer']]],
  ['result_5ftype',['result_type',['https://doc.qt.io/qt-5/qrandomgenerator.html#result_type-typedef',0,'QRandomGenerator::result_type()'],['https://doc.qt.io/qt-5/qrandomgenerator64.html#result_type-typedef',0,'QRandomGenerator64::result_type()']]],
  ['reverse_5fiterator',['reverse_iterator',['https://doc.qt.io/qt-5/qbytearray.html#reverse_iterator-typedef',0,'QByteArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qstringview.html#reverse_iterator-typedef',0,'QStringView::reverse_iterator()'],['https://doc.qt.io/qt-5/qlatin1string.html#reverse_iterator-typedef',0,'QLatin1String::reverse_iterator()'],['https://doc.qt.io/qt-5/qstring.html#reverse_iterator-typedef',0,'QString::reverse_iterator()'],['https://doc.qt.io/qt-5/qlist.html#reverse_iterator-typedef',0,'QList::reverse_iterator()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reverse_iterator-typedef',0,'QVarLengthArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qvector.html#reverse_iterator-typedef',0,'QVector::reverse_iterator()'],['https://doc.qt.io/qt-5/qset.html#reverse_iterator-typedef',0,'QSet::reverse_iterator()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reverse_iterator-typedef',0,'QLinkedList::reverse_iterator()']]]
];
